# Generated by Django 3.0.3 on 2020-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200218_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping_count',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
